apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
      - name: argoce-app
        image: thiexco/argocd-app:v2025-07-12-15-17-04
        ports:
        - containerPort: 5000
