name: Test and Build CI

on: 
  push:
    branches:
      - main
    paths:
      - '**/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code and set up Python environment
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Docker setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          pip install pytest

      # Testing the code
      - name: Run Linting Tests
        run: |
          flake8 --ignore=E501,F401 .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Create image tag
      - name: Generate image tag
        id: version
        run: |
          VERSION=v$(date +'%Y%m%d%H%M%S')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Debug: Print image tag
      - name: Echo version
        run: |
          echo "Docker image tag will be: ${{ env.VERSION }}"

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t ${{ secrets.DOCKER_USERNAME }}/argocd-app:${{ env.VERSION }} .

      # Push again (optional step - can be removed since --push already did it)
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/argocd-app:${{ env.VERSION }}
