name: Test and Build CI 
on: 
  push:
    branches:
      - main
    paths:
      - '**/*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code and set up Python environment
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Docker setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          pip install pytest

      #Testing the code
      - name: Run Linting Tests
        run: |
          flake8 --max-line-length=88 --ignore=E501,E203,E231,E402,W503 .
          python -m pytest --maxfail=1 --disable-warnings -q
      
      # set up Docker credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # create tag
      - name: docker tag
        id: version
        run: |
          VERSION=v$(date +'%Y%m%d%H%M%S')
          echo "version=$VERSION" >> $GITHUB_ENV

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push -t ${{ secrets.DOCKER_USERNAME }}/argocd-app:${{ env.VERSION }} .
      
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/argocd-app:${{ env.VERSION }}